version: '2'
services:
    mongodb:
        image: mongo:latest
        container_name: "mongodb_spring"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/mongo:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet
    java:
        build:
          context: .
        depends_on:
            - mongodb
        ports:
          - 8080:8080
